### PR TITLE
Handle the change in property name to get the router in express 5

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by jasisk** [comment]
Gonna need some more intensive duck typing. Express 4 throws because deprecated. Heh.

**Comment by aredridel** [comment]
Oh geez, throws. Grr.

**Comment by aredridel** [comment]
Flipped it around so it uses the express 4 way first.

**Comment by jasisk** [comment]
Will this throw misleading deprecation warnings in Express 5?

**Comment by aredridel** [comment]
Nope. It's undefined in express 5 -- since it was private, there was no move to deprecate it.

**Comment by jasisk** [comment]
:+1:

**Pull request merged**
