### PR TITLE
Fix edge case with local resolve - fixes #81

### LINKED ISSUE #81: edge case bug in the local path resolver
[Plonk](https://github.com/krakenjs/meddleware/blob/a7967875695828dd3a73e4ac5bd5ccb8c69efa70/index.js#L89).

[`tryRequire` just calls `require.resolve`](https://github.com/krakenjs/meddleware/blob/a7967875695828dd3a73e4ac5bd5ccb8c69efa70/lib/util.js#L62) which will, for local files, start relative to the file that contains it.

Therefore, if you try to require a file with a relative path that _could_ resolve to a similarly named file from the `util` folder in meddleware, :boom:.

Proof:
``` sh
$ echo "console.log('i am required');" > rq.js

$ cat - > index.js <<EOF
const meddleware = require('meddleware');
const express = require('express');

const app = express();

const config = {
  example: {
    module: './rq.js'
  }
};

app.use(meddleware(config));
EOF

$ node index.js
/cat/city/secret/path/node_modules/meddleware/index.js:100
            throw new Error('Unable to locate middleware in ' + config.name);
            ^

Error: Unable to locate middleware in ./rq.js
```

### PR DESCRIPTION
**Pull request by shaunwarman**
It looks as though we [get the caller](https://github.com/krakenjs/meddleware/blob/v3.x/index.js#L181-L183) and pass this basedir around. We should be able to safely use this absolute path.

Seems to be mentioned here:
https://github.com/krakenjs/meddleware/blob/v3.x/index.js#L181-L183

> // The `require`-ing module (caller) is considered the `basedir`
> // against which relative file paths will be resolved.
> // Don't like it? Then pass absolute module paths. :D

### CODE REVIEW

**Comment by grawk** [comment]
👍

**Comment by jasisk** [comment]
Won't this change break every non-local require?

**Comment by grawk** [comment]
Ah thanks for chiming in. I was looking at the code in another context just now and realized I was probably hasty in my approval.

**Comment by shaunwarman** [comment]
Doesn't [`caller()`](https://github.com/krakenjs/meddleware/blob/v3.x/index.js#L184) give us an absolute path?

**Comment by shaunwarman** [comment]
Oops, no.. you're right.

**Comment by jasisk** [comment]
👊✋️🎤

**Pull request closed without merging**
